version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # ✅ load env vars from .env file
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
